spring:
  application:
    name: book
  config:
    import: optional:configserver:http://localhost:8089/
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: '*'
resilience4j:
  circuitbreaker:
    instances:
      findAllByAuthorId:
        registerHealthIndicator: true
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        ignoreExceptions:
          - com.igorcossta.common.exception.AuthorNotFoundException
          - com.igorcossta.common.exception.AuthorHasNoBookException