server:
  port: 8080
spring:
  # initialize mysql database using
  # docker container run -dp 3306:3306 --name author-mysql -e MYSQL_ROOT_PASSWORD=123 -e MYSQL_DATABASE=author mysql:latest
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/author
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
ribbon:
  eureka:
    enabled: false
